// <auto-generated />
namespace Pocket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class expcomments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(expcomments));
        
        string IMigrationMetadata.Id
        {
            get { return "201407011410551_expcomments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
