// <auto-generated />
namespace Pocket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class mansoor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mansoor));
        
        string IMigrationMetadata.Id
        {
            get { return "201401031539082_mansoor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
